# Generated by Django 3.2.5 on 2021-09-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210911_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='anonymous',
            field=models.BooleanField(default="False"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='type',
            field=models.CharField(max_length=1),
        ),
    ]
