# Generated by Django 3.2.5 on 2021-09-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210914_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.JSONField(default=list),
        ),
    ]
