# Generated by Django 3.2.5 on 2021-09-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='donation',
        ),
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
