# Generated by Django 3.2.5 on 2021-09-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210924_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='donation',
            field=models.IntegerField(default=0),
        ),
    ]
