# Generated by Django 3.2.5 on 2021-09-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='goal',
        ),
    ]
