# Generated by Django 3.2.5 on 2021-09-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
