# Generated by Django 3.2.5 on 2021-09-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='donation',
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.IntegerField(default=0),
        ),
    ]
